language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
node_js:
  - v9
  - v8
before_install:
  - npm install -g coveralls
script:
  - npm run build
  - npm run test:lint
  - npm run test:tslint
  - npm run test:coverage
after_success:
  - npm run build:docs
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  # Disabled while working on TS rewrite
  # - npm run semantic-release
