dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
language: node_js
services: mysql
env:
  - KLAY_MYSQL_HOST=localhost KLAY_MYSQL_DB=klay_kiln_sql KLAY_MYSQL_USER=root
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v7
  - v6
before_install:
  - npm install -g coveralls
before_script:
  - mysql -e 'create database if not exists klay_kiln_sql;' -u root
script:
  # - npm run build
  # - npm run test:tslint
  # - npm run test:unit
  # disabled until klay-db is published
  - /bin/true
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  # - npm run semantic-release
