dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
language: node_js
services: mysql
env:
  - KLAY_MYSQL_HOST=localhost KLAY_MYSQL_DB=klay_kiln_express KLAY_MYSQL_USER=root
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v6
  - v5
  - v4
before_install:
  - npm install -g coveralls
before_script:
  - npm prune
  - mysql -e 'create database if not exists klay_kiln_express;' -u root
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  # - npm run semantic-release
