language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v9
  - v8
before_install:
  - npm install -g coveralls nyc
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - nyc report --reporter=text-lcov | coveralls || echo 'Failed to upload to coveralls...'
  # - npm run semantic-release
