language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v8
  - v7
  - v6
before_install:
  - npm install -g coveralls
script:
  - npm run build
  - npm run test:lint
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  # Disabled while working on TS rewrite
  # - npm run semantic-release
